### ISSUE TITLE
List of Known Bugs

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Parozzz/HopeItems#1]
I'm not sure if you have a list where you add bugs/things to do when I report them on discord, and I like things to be organized/all in one place. So I created this. I'm also aware you likely don't/won't have time to fix all of these. So it's also for anyone that wants to fork it (if you allow that).

Crossed out text means it's been solved in current or upcoming versions.

**Basic Information if Needed:**
Server Version: https://gyazo.com/a49dadbdf84cf4711cb2b6edf00bf691
Plugins: https://gyazo.com/2ef681c3f1d360a3ddc4e70717481933
HopeItems Version: V2_3.2

**1.)** ~~The wiki cooldown page says "Each item has its own cooldown separated from the others."
When I tested it, I placed multiple blocks of the same type. The block was supposed to feed me when I walked across it, with a 10 second cooldown per block. It did for the first block, then the other blocks said I needed to wait for the cooldown. Meaning all blocks of the same type have the same cooldown time.~~ Update: It's supposed to be this way. It was unclear in the wiki.

**2.)** ~~Actions do not support doing them against mobs. At least, that's what you told me needs to be done. The item I tested was a snowball meant to give the person/mob it hit slowness II for 5 seconds. It worked on players, but not mobs.~~

**3.)** ~~Using the projectile when, if a player launches a projectile and it hits a player, it will perform the action (good). Unfortunately, if the player misses, it will perform the action on the player who launched the projectile (bad). This was tested with a snowball that was meant to give a person slowness II for 5 seconds.~~
**Parozzz added a list of possibilities.**
* Always affect the shooter
* Always and only affect the damaged
* A mutual thing (Missed = shooter, hit = damaged)
* Always affect both the shooter and the damaged (If hit)(edited)
**By default will be mutual, but you can change it how you want.**

**4.)** ~~I'm not sure if this can be fixed. So it may not be a bug but I'll put it here just in case. It kind of goes with 2 and 3. When launching a projectile at a player, it will only perform the action if pvp is enabled using whatever plugins are on the server that manage pvp (such as Worldguard or Residence). This can be good sometimes and can be bad. It'd be nice if there were an option that allowed it to bypass the pvp flag setting.~~ **Added overidePvpProtection feature.**

**5.)** I forgot the others. I'll update this if I remember.

**Comment by PiggiesGoSqueal** [comment]
**5.)** ~~The addFood: action will add more food than the hunger bar can hold. Meaning if a player uses an item or block that adds food a lot of times, they can go a long time without eating food. Note: I'm guessing this is an issue for health too.
My hunger after using the addFood action a ton:~~
https://gyazo.com/514f7b79ba688ca70ea806c7fd0e9598

**Comment by PiggiesGoSqueal** [comment]
**6.)** If you have a placed custom block that does an action when walked upon, it will do the action even if the player is standing on a slab that's on top of the custom block.

**7.)** ~~Placed Custom Blocks Become normal blocks~~
  - ~~Steps to reproduce:~~
    * ~~There's an error with the plugin. For example, typing something wrong in an item setup then reloading the plugin.~~
    * ~~Restarting the server. Meaning, that error is still an issue and causes the plugin to not load on startup.~~
    * ~~Fixing the error from the wrong item setup.~~
    * ~~Restarting the server.~~
    * ~~Testing an already placed custom block (from before starting this whole process).~~
    * ~~This removed the custom blocks and made them normal blocks. Which is a huge issue when players spent diamonds to craft those custom blocks, and now they're gone.~~

**8.)** It's not possible to add an amount requirement for items in a recipe. It should be according to wiki but it only takes 1 to craft the item when it's supposed to take 32. 
My format: https://pastebin.com/RMvN7bf8

**Comment by pinkpig3777** [comment]
**8.)** I have an item that bans a player when they mine it. And I had it in my inventory and broke a block while holding it. It banned me. Lol..

**Comment by Parozzz** [comment]
All fixed (Except for 6) in v3_BETA1 version.
